apiVersion: v1
kind: Service
metadata:
  name: ai-connector-service
  labels:
    app: ai-connector-service
spec:
  selector:
    app: ai-connector-service
  ports:
    - name: http
      port: 8001
      targetPort: 8001
  type: ClusterIP
