## ArgoCD Helm values for local GitOps environment
## Chart: argo/argo-cd v9.4.17

global:
  domain: argocd.local

server:
  extraArgs:
    - --insecure
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - argocd.local
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web

configs:
  params:
    server.insecure: true

  cm:
    url: "http://argocd.local"
    admin.enabled: "true"
    oidc.config: |
      name: Keycloak
      issuer: http://keycloak.local/realms/gitops
      clientID: argocd
      clientSecret: 18cc30bcf8c5cd04cb4e25cdab7ab330d6abb858d7c9cb8e
      requestedScopes:
        - openid
        - profile
        - email

  rbac:
    policy.default: role:readonly
    policy.csv: |
      g, admin, role:admin

  repositories:
    gitea-gitops-infra:
      url: http://gitea:3000/platform/gitops-infra.git
      name: gitops-infra
      type: git
      username: "gitea_admin"
      password: "Xjf0tARw4fjL4zrZin7GOxYWxwExwSvL"
    # Add your application repos below, for example:
    # gitea-my-app:
    #   url: http://gitea:3000/platform/my-app.git
    #   name: my-app
    #   type: git
    #   username: "gitea_admin"
    #   password: "Xjf0tARw4fjL4zrZin7GOxYWxwExwSvL"

controller:
  replicas: 1

repoServer:
  replicas: 1

redis:
  enabled: true

notifications:
  enabled: false
