#!/usr/bin/env bash
# Master bootstrap script - sets up the entire local GitOps environment
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo ""
echo "=============================================="
echo "  Local GitOps Landing Zone - Bootstrap"
echo "=============================================="
echo ""

run_step() {
  local step="$1"
  local desc="$2"
  echo ""
  echo "----------------------------------------------"
  echo "  Step: $desc"
  echo "----------------------------------------------"
  bash "$SCRIPT_DIR/$step"
}

run_step "setup-hosts.sh"            "Configure local DNS (hosts file)"
run_step "00-prerequisites.sh"       "Install prerequisites (k3d, helm, argocd CLI)"
run_step "01-create-network.sh"      "Create shared Docker network"
run_step "02-start-gitea.sh"         "Start Gitea stack"
run_step "03-configure-gitea.sh"     "Configure Gitea (admin, org, runner)"
run_step "04-create-k3d-cluster.sh"  "Create k3d Kubernetes cluster"
run_step "05-install-metallb.sh"     "Install MetalLB load balancer"
run_step "06-install-argocd.sh"      "Bootstrap ArgoCD"
run_step "07-push-gitops-repo.sh"    "Push gitops-infra repo to Gitea"
run_step "07b-push-app-repos.sh"     "Push app repos (bankoffer-platform, careerforge) to Gitea"
run_step "08-configure-argocd-repo.sh" "Register Gitea repo in ArgoCD"
run_step "09-apply-app-of-apps.sh"   "Activate app-of-apps"
run_step "09b-build-portal.sh"       "Build + import landing portal image"
run_step "09c-build-app-images.sh"   "Build + import application images (slides, bankoffer-api)"
run_step "10-configure-oidc.sh"      "Configure Keycloak OIDC SSO"

echo ""
echo "=============================================="
echo "  Bootstrap Complete!"
echo "=============================================="
echo ""
echo "  Platform:"
echo "    Portal:     http://portal.local"
echo "    Gitea:      http://gitea.local:3000  — gitea_admin (see .env)"
echo "    ArgoCD:     http://argocd.local      — admin (see .env)"
echo "    Keycloak:   http://keycloak.local    — admin (see .env)"
echo "    Grafana:    http://grafana.local      — admin (see .env)"
echo "    Prometheus: http://prometheus.local"
echo "    Vaultwarden: https://localhost:8443"
echo ""
echo "  BankOffer AI:"
echo "    Employee Portal: http://bankoffer.local"
echo "    Admin Portal:    http://bankoffer.local/admin"
echo "    API Docs:        http://bankoffer.local/docs"
echo "    Slides:          http://bankoffer-slides.local"
echo ""
echo "  CareerForge:"
echo "    Admin:     http://cf-admin.local"
echo "    Coach:     http://cf-coach.local"
echo "    Employee:  http://cf-employee.local"
echo "    Slides:    http://cf-slides.local"
echo ""
echo "  All credentials are in .env"
echo "  SSO accounts: dev / dev (Keycloak gitops realm)"
echo "  Run 'kubectl get applications -n argocd' to check sync status"
echo "=============================================="
