---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bankoffer-slides
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://gitea:3000/platform/gitops-infra.git
    targetRevision: main
    path: manifests/bankoffer-slides
  destination:
    server: https://kubernetes.default.svc
    namespace: bankoffer-slides
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
