apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bankoffer
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: http://gitea:3000/platform/bankoffer-platform.git
      targetRevision: main
      path: infra/helm/bankoffer
      helm:
        releaseName: bankoffer
        valueFiles:
          - $values/manifests/bankoffer/values.yaml
    - repoURL: http://gitea:3000/platform/gitops-infra.git
      targetRevision: main
      ref: values
    - repoURL: http://gitea:3000/platform/gitops-infra.git
      targetRevision: main
      path: manifests/bankoffer/extra
  destination:
    server: https://kubernetes.default.svc
    namespace: bankoffer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
