apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: careerforge
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: http://gitea:3000/platform/careerforge.git
    targetRevision: main
    path: kustomize/overlays/landing-zone
  destination:
    server: https://kubernetes.default.svc
    namespace: careerforge
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
