apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-postgres
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: http://gitea:3000/platform/gitops-infra.git
    targetRevision: main
    path: manifests/keycloak-postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
