apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: http://gitea:3000/platform/gitops-infra.git
    targetRevision: main
    path: manifests/local-ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
