apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portal
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: dev
  source:
    repoURL: http://gitea:3000/platform/gitops-infra.git
    targetRevision: main
    path: manifests/portal
  destination:
    server: https://kubernetes.default.svc
    namespace: portal
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
