FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
COPY presentation.html /usr/share/nginx/html/presentation.html
COPY BankOffer_AI_Presentation.html /usr/share/nginx/html/BankOffer_AI_Presentation.html
COPY users.html /usr/share/nginx/html/users.html
EXPOSE 80
