apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: careerforge-app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://git.lupulup.com/careerforge/platform.git
    targetRevision: HEAD
    path: argocd/apps
    directory:
      recurse: false
      exclude: app-of-apps.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
