apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgres-secret
  namespace: keycloak
  labels:
    app: keycloak-postgres
type: Opaque
stringData:
  username: keycloak
  password: "6fnotwzRl750ibwXM2s7J0aUUd9XCZL8"
  database: keycloak
