apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgres-secret
  namespace: keycloak
  labels:
    app: keycloak-postgres
type: Opaque
stringData:
  username: keycloak
  password: "${KEYCLOAK_DB_PASSWORD}"
  database: keycloak
