---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: careerforge-dev-keys
  namespace: careerforge
spec:
  encryptedData:
    hmac_key_hex: AgBr/qWVEnwT23ucx+zUmVArGgaQxcRI+CbEWBE86c+PaTEinGDDqu++09JU9xFezoNRHjU1CejLlqY3BXgqNlAN3SoMxsRYyMN60KH7GgOx5MiNFd7IEyv3YX1vkO3BlQpdJSioW33S+RchC/+OY6SH0DmObdfQlSmGkPpVG5CTByUNdVlXZk3vP/6Vd8eMEXQFOKP2P6xIV2vi4e3Yf6Nz+nrPTwCJgDO+0R7162PTICKrXLUcvAKXFGFJbgiHJ28CeOt1r8qKyhl/GhemS+eU4nsywN6Hf1bphwcsevwwULQl158u83Z8EWANDN1AZDjpb8W5ltnaOs7/dU/kyShx3oTupp8BaYhit0m0wVa20+LMrYFAD3B6mrOqJq1QRusSGux6SNZBPFWuUWhTUih/zfVR1za8nqSmL8ND+sAA9NL6x01FqnHGTg8R17FFz2TyEJgeC42impfRV/KJ9vLzRfhsjzNHR2UdNyqd9Xrd871gPP1IYKAdBMl1sLTbsFptIXqKC8ZeGqu3ym8pljYlzI42lN3DcFrmXa90a5/vASnRasTfb6kdkWxu5JKOqK2EgorMmSIdqVcVv11iLKPh8Km1UbI/qhX6zcAetlCC2kTdy542jleD7omjqu1bCT0D4Zbh+OiTcBiEP+9JIeD5KHLHIbHkp4N6Zhc7hmAwhYapApU1E+JK9wzkR5aCNJiVeFUdpq7amcR99GPplg/AXVscC/Dx3XAnjPM6prbFhZodw+XslcS2fymirbZ8CoStddqZWNlIVn+8SG3+NvOr
    pii_key_hex: AgB13dKi7sWT//G+BTkV4LkUC2AZm5sivRHzp7IURA1xQtQgtJ7PB8wcdrHpWOG4BmowuYQBF/Q68joCmzHriRvSe8snId6AFScu9iDPDomTTIWZQ2/kTPsrNycBT0pCyWSEmv1q4vWEOP9ycxHdZNBi2w8b3wntWWWSuckQ1TOClJuwk3lEK7rxTBWMJzeVfqE9Iqkiq23LGy+ngXZiGIyZt824a/hxYoLtSIuiNOpg3FtaqVpJ/SsdWKuSse9kV9kDtu1+henvWBR4pK1seG4pTfM5CXMt6h1riAePZg4Tv13l3VdHhtXM/kCzJnTC4qb60M0pGNo8/8Q24aFBo3msJdHvi6g5zugcvi0OajF+mHpHlUwLi/U7M3j9sfF+NB/QVsjdDMJzsy1nPnwpmr3wpUH0dMwFHnMb5H6ODb7FkRA1BYDh0+R19hqa3dnQHRRF1EC7N3Tk8f4K4fV7odwEAsGUcEMAB6uZh6sy0bMYh9gPxAH9iA+HrJu9qldjS6BnlubAvT/OClak420nwDuBZaitHcR5jtxhWR9+KNentRtDdi+T+KtyLGdlORt4xecwB+v01JX94Jv0BI6jiA+f++RTXGeFDSgG/FYCsGuLhs4kRrz+13Ll5CzHBvnfElrvzqFI2pFVPV+WLS4qOGiMG/nR2iTEfKr/eteHu6fT3nO790cmufWsPPFV6tyM56E9K4ZRHHOPkLeTnku7ufs3ekigKqR2uf/ffcwy8SMFZj4aI1WYZwasyTxVVS3LbGRwp8o4CAJVGfOs1YG7R+K5
  template:
    metadata:
      creationTimestamp: null
      name: careerforge-dev-keys
      namespace: careerforge
    type: Opaque
